# 11_tables.R
# -----------------------------------------------------------------------------
# Assemble the analysis outputs into the manuscript tables, as GitHub-flavoured
# Markdown, written to data/results/manuscript_tables.md.
#
# One block per Tab_* token used in the manuscript:
#   Tab_Samples, Tab_SiteEffect, Tab_MarkerDiversity, Tab_NullAlleles,
#   Tab_Survival, Tab_GrowthAIC, Tab_GrowthHeritability, Tab_OriginHeritability,
#   Tab_RepeatedAIC, Tab_RepeatedHeritability, Tab_CovariateEffects
#
# These are drafts to reconcile into Tables.md (Phase 3); numbers come straight
# from the result CSVs in data/results/.
# -----------------------------------------------------------------------------

source("R/00_setup.R")
suppressPackageStartupMessages({ library(readr); library(dplyr); library(tidyr); library(purrr); library(stringr) })

rd <- function(f) read_csv(file.path(paths$results, f), show_col_types = FALSE)
out <- file(file.path(paths$results, "manuscript_tables.md"), "w")
w   <- function(...) writeLines(paste0(...), out)

md_table <- function(df, digits = 3) {
  fmt_num <- function(x) {
    if (all(is.na(x) | x == round(x))) return(ifelse(is.na(x), "—", as.character(as.integer(x))))
    ifelse(is.na(x), "—", formatC(x, format = "f", digits = digits))
  }
  df <- df %>% mutate(across(where(is.numeric), fmt_num))
  hdr  <- paste0("| ", paste(names(df), collapse = " | "), " |")
  sep  <- paste0("| ", paste(rep("---", ncol(df)), collapse = " | "), " |")
  body <- apply(df, 1, function(r) paste0("| ", paste(r, collapse = " | "), " |"))
  c(hdr, sep, body)
}
ci <- function(est, lo, hi, d = 3) ifelse(is.na(est), "—",
  sprintf(paste0("%.", d, "f [%.", d, "f, %.", d, "f]"), est, lo, hi))
star <- function(p) ifelse(is.na(p), "", ifelse(p < .001, "***", ifelse(p < .01, "**", ifelse(p < .05, "*", ifelse(p < .1, "·", "")))))

w("# Tables\n")
w("<!-- Generated by R/11_tables.R from data/results/*.csv. Numbers are from the",
  " reproducible pipeline (rearing location not a model term; Admixture Percentage",
  " a continuous fixed covariate; 1000-replicate parametric-bootstrap 95% CIs). -->\n")

# ---- Tab_Samples ------------------------------------------------------

seed <- rd("../../data/derived/seedlings.csv")
surv <- rd("../../data/derived/survival.csv")
samp <- seed %>% count(origin, mom, name = "Beginning") %>%
  left_join(surv %>% group_by(mom) %>% summarise(End = sum(alive_final)), by = "mom") %>%
  arrange(origin, mom)
w("\n## Tab_Samples\n")
w("Seedlings per maternal family at the start of the common garden and alive at the final census.\n")
writeLines(md_table(samp %>% transmute(Origin = origin, Family = mom, Beginning, End), digits = 0), out)

# ---- Tab_SiteEffect --------------------------------------------------

se <- rd("site_effect.csv")
w("\n## Tab_SiteEffect\n")
w("Likelihood-ratio test of native collection site (Pocahontas State Park vs Rice Rivers Center) ",
  "on survival and each growth trait, native-origin seedlings only.\n")
writeLines(md_table(se %>% transmute(Response = response, n,
  `Site coefficient` = site_estimate, SE = site_se, `chi-sq` = chisq, df, p)), out)

# ---- Tab_MarkerDiversity -------------------------------------------

md  <- rd("marker_diversity.csv")
pe  <- rd("exclusion_probability.csv") %>% filter(set == "per-locus")
mdx <- md %>% left_join(pe %>% select(Locus, Pe), by = "Locus")
w("\n## Tab_MarkerDiversity\n")
w("Per-locus diversity across the nine cultivar-diagnostic microsatellite loci for ",
  "the maternal trees and their offspring arrays: number of alleles (A), effective ",
  "number of alleles (Ae), observed and expected heterozygosity (Ho, He), inbreeding ",
  "coefficient (F_IS), and single-locus exclusion probability (Pe).\n")
writeLines(md_table(mdx %>% transmute(Group = group, Locus, A, Ae, Ho, He, `F_IS` = Fis,
  Pe = ifelse(is.na(Pe), NA, round(Pe, 3)))), out)

# ---- Tab_NullAlleles ---------------------------------------------

na_tbl <- rd("null_alleles.csv")
excl   <- rd("exclusion_probability.csv")
red_loci <- readLines(file.path(paths$derived, "reduced_marker_set.txt"))
w("\n## Tab_NullAlleles\n")
w("Maximum-likelihood estimates of null-allele frequency per locus for the cultivar- ",
  "and native-origin samples (Genepop; Rousset 2008), with 95% confidence intervals.\n")
na_wide <- na_tbl %>%
  mutate(val = sprintf("%.4f [%.4f, %.4f]", null_est, ci_low, ci_high),
         val = ifelse(is.na(ci_low), sprintf("%.4f", null_est), val)) %>%
  select(Locus, population, val) %>%
  pivot_wider(names_from = population, values_from = val) %>%
  mutate(`In reduced set` = ifelse(Locus %in% red_loci, "yes", "no"))
writeLines(md_table(na_wide, digits = 4), out)
w("")
w("Combined multilocus exclusion probability (gstudio; Dyer 2009):\n")
writeLines(md_table(excl %>% filter(set != "per-locus") %>%
  transmute(`Marker set` = set,
            `P(exclusion), multilocus` = signif(Pe, 5)), digits = 5), out)

# ---- Tab_Survival ----------------------------------------------

sa <- rd("survival_aic.csv"); sq <- rd("survival_quantgen.csv")
sq_w <- sq %>% select(set, parameter, estimate, ci_low, ci_high) %>%
  pivot_wider(names_from = parameter, values_from = c(estimate, ci_low, ci_high))
surv_tab <- sa %>%
  mutate(join_set = case_when(
    subset == "Total"    & model == "family"          ~ "Total_family",
    subset == "Total"    & model == "origin + family" ~ "Total_origin_family",
    subset == "Native"   & model == "family"          ~ "Native_family",
    subset == "Cultivar" & model == "family"          ~ "Cultivar_family",
    subset == "AP"       & model == "family"          ~ "AP_family",
    TRUE ~ NA_character_)) %>%
  left_join(sq_w, by = c("join_set" = "set")) %>%
  transmute(Subset = subset, Model = model,
            AICc = round(AICc, 2), dAICc = round(dAICc, 2), wAICc = round(wAICc, 3),
            `V origin` = ci(estimate_V_origin, ci_low_V_origin, ci_high_V_origin),
            `V family` = ci(estimate_V_family, ci_low_V_family, ci_high_V_family),
            `P family` = ifelse(is.na(estimate_P_family), "—", sprintf("%.3f", estimate_P_family)),
            h2 = ci(estimate_h2, ci_low_h2, ci_high_h2))
w("\n## Tab_Survival\n")
w("Binomial GLMM model selection and latent-scale quantitative-genetic parameters ",
  "for survival, with 1000-replicate bootstrap 95% CIs. AP is a fixed covariate ",
  "(the AP rows compare family vs AP + family).\n")
writeLines(md_table(surv_tab %>% mutate(across(where(is.numeric), as.character))), out)

# ---- Tab_GrowthAIC ------------------------------------------

ga <- rd("growth_aic.csv")
trait_lab <- c(height = "Plant height", stem_diam = "Stem diameter",
  leaf_number = "Number of leaves", AGB = "Above-ground biomass",
  BGB = "Below-ground biomass", leaf_biomass = "Leaf biomass", stem_biomass = "Stem biomass")
w("\n## Tab_GrowthAIC\n")
w("Model comparison for the single-time growth traits.\n")
for (tr in names(trait_lab)) {
  w("\n**", trait_lab[[tr]], "**\n")
  writeLines(md_table(
    ga %>% filter(trait == tr) %>%
      transmute(Subset = subset, Model = model,
        AIC = round(AIC, 1), dAIC = round(dAIC, 1), wAIC = round(wAIC, 2),
        AICc = round(AICc, 1), dAICc = round(dAICc, 1), wAICc = round(wAICc, 2)) %>%
      mutate(across(where(is.numeric), as.character)), digits = 2), out)
}

# ---- Tab_GrowthHeritability + Tab_OriginHeritability -------

fmt_qg <- function(df) {
  df %>% transmute(
    Trait = trait_lab[trait], Model = model, Sensitivity = sensitivity,
    Removed = ifelse(is.na(removed), "—", removed),
    `V origin` = ifelse(is.na(estimate_V_origin), "—",
      paste0(ci(estimate_V_origin, ci_low_V_origin, ci_high_V_origin), star(p_origin))),
    `V family` = paste0(ci(estimate_V_family, ci_low_V_family, ci_high_V_family), star(p_family)),
    `V residual` = ci(estimate_V_residual, ci_low_V_residual, ci_high_V_residual),
    h2 = ci(estimate_h2, ci_low_h2, ci_high_h2))
}
gq <- rd("growth_quantgen.csv"); goq <- rd("growth_origin_quantgen.csv")
w("\n## Tab_GrowthHeritability\n")
w("Variance components and half-sib heritability for the single-time traits, with a ",
  "sensitivity pass (drop |residual z| > 3 observations; drop the most influential family). ",
  "Significance from ranova: · p<0.1, * p<0.05, ** p<0.01, *** p<0.001.\n")
writeLines(md_table(fmt_qg(gq) %>% mutate(across(everything(), as.character)), digits = 3), out)
w("\n## Tab_OriginHeritability\n")
w("Within-origin variance components and heritability (family model only).\n")
writeLines(md_table(
  goq %>% transmute(Trait = trait_lab[trait], Subset = subset, Sensitivity = sensitivity,
    Removed = ifelse(is.na(removed), "—", removed),
    `V family` = paste0(ci(estimate_V_family, ci_low_V_family, ci_high_V_family), star(p_family)),
    `V residual` = ci(estimate_V_residual, ci_low_V_residual, ci_high_V_residual),
    h2 = ci(estimate_h2, ci_low_h2, ci_high_h2)) %>%
    mutate(across(everything(), as.character)), digits = 3), out)

# ---- Tab_RepeatedAIC + Tab_RepeatedHeritability -----------

ra <- rd("repeated_aic.csv"); rq <- rd("repeated_quantgen.csv")
w("\n## Tab_RepeatedAIC\n")
for (tr in c("height", "stem_diam", "leaf_number")) {
  w("\n**", trait_lab[[tr]], "**\n")
  writeLines(md_table(ra %>% filter(trait == tr) %>%
    transmute(Model = model, AIC = round(AIC, 1), dAIC = round(dAIC, 1), wAIC = round(wAIC, 2),
      AICc = round(AICc, 1), dAICc = round(dAICc, 1), wAICc = round(wAICc, 2)) %>%
    mutate(across(where(is.numeric), as.character)), digits = 2), out)
}
w("\n## Tab_RepeatedHeritability\n")
writeLines(md_table(rq %>% transmute(
  Trait = trait_lab[trait], Model = model, Sensitivity = sensitivity,
  `V origin` = ifelse(is.na(estimate_V_origin), "—",
    paste0(ci(estimate_V_origin, ci_low_V_origin, ci_high_V_origin), star(p_origin))),
  `V family` = paste0(ci(estimate_V_family, ci_low_V_family, ci_high_V_family), star(p_family)),
  `V plant` = paste0(ci(estimate_V_plant, ci_low_V_plant, ci_high_V_plant), star(p_plant)),
  h2 = ci(estimate_h2, ci_low_h2, ci_high_h2)) %>%
  mutate(across(everything(), as.character)), digits = 3), out)

# ---- Tab_CovariateEffects --------------------------------
# Publication layout: one row per response x subset, one column per covariate,
# showing the coefficient with its standard error and a significance mark.
# Panel A: survival (logit scale). Panel B: growth traits (ln scale).

coef_cell <- function(est, se, p) {
  ifelse(is.na(est), "—",
    sprintf("%+.3f (%.3f)%s", est, se, star(p)))
}

sfe <- rd("survival_fixed_effects.csv") %>%
  filter(model %in% c("full_family", "native_family", "cultivar_family"),
         term %in% c("days_z", "seed_weight_z")) %>%
  mutate(subset = recode(model, full_family = "Total", native_family = "Native",
                         cultivar_family = "Cultivar"),
         term = recode(term, days_z = "Germination timing", seed_weight_z = "Seed weight")) %>%
  transmute(Response = "Survival", Subset = subset, term, cell = coef_cell(estimate, se, p)) %>%
  pivot_wider(names_from = term, values_from = cell)

gcov <- rd("growth_covariates.csv") %>%
  mutate(Response = trait_lab[trait],
         term = recode(term, days_z = "Germination timing", seed_weight_z = "Seed weight")) %>%
  filter(term %in% c("Germination timing", "Seed weight")) %>%
  transmute(Response, Subset = subset, term, cell = coef_cell(estimate, se, p)) %>%
  pivot_wider(names_from = term, values_from = cell)

cov_tab <- bind_rows(sfe, gcov) %>%
  mutate(Response = factor(Response, levels = c("Survival", unname(trait_lab))),
         Subset = factor(Subset, levels = c("Total", "Native", "Cultivar"))) %>%
  arrange(Response, Subset) %>%
  select(Response, Subset, `Germination timing`, `Seed weight`)

w("\n## Tab_CovariateEffects\n")
w("Estimated effects of the two family-level covariates on survival (logit scale) ",
  "and each growth trait (ln scale), from the family model, for the full sample and ",
  "within each origin class. Cells give the coefficient (SE). Germination timing is ",
  "scaled developmental time since germination (higher = earlier germination, more ",
  "growing time); seed weight is the scaled maternal family mean. ",
  "· p<0.1, * p<0.05, ** p<0.01, *** p<0.001.\n")
writeLines(md_table(cov_tab), out)

# ---- Tab_GerminationTiming -------------------------------------
# Does origin predict germination timing itself? (Methods lists GD as a trait.)

gt_file <- file.path(paths$results, "germination_timing.csv")
if (file.exists(gt_file)) {
  gt <- rd("germination_timing.csv")
  w("\n## Tab_GerminationTiming\n")
  w("Model comparison and quantitative-genetic parameters for germination timing ",
    "(developmental time since germination). Origin was tested as a random effect; ",
    "the germination-timing covariate is omitted because it is the response.\n")
  writeLines(md_table(gt %>% transmute(Component = what, Term = model, Value = value)), out)
}

close(out)
message("wrote ", file.path(paths$results, "manuscript_tables.md"))
